-- ⚠️ 이 파일은 더 이상 사용하지 않습니다.
--
-- 이전 버전(이메일/비밀번호 로그인) 에서 12명 계정을 일괄 생성하는 시드였지만,
-- 이제는 Google OAuth 로 인증하므로 멤버가 직접 Google 로그인하면 자동으로 계정이 생깁니다.
--
-- 누가 접속할 수 있는지는 Supabase 의 `allowed_emails` 테이블이 결정합니다.
-- 이메일 추가/삭제는 Dashboard → Table Editor → allowed_emails 에서 직접.
